### get cats
GET http://localhost:3000/api/v1/cats

### create cats
POST http://localhost:3000/api/v1/cats
Content-Type: application/json

{
    "name": "patroclo",
    "age": 2,
    "breed": "callejero"
}

### get cats by id
GET http://localhost:3000/api/v1/cats/75c50826-6953-49d2-a72c-3111ff8b5aac

### delete cats
DELETE http://localhost:3000/api/v1/cats/75c50826-6953-49d2-a72c-3111ff8b5aac

### create cats
PATCH http://localhost:3000/api/v1/cats/bf37cb27-0a59-443e-961e-29555c00ad90
Content-Type: application/json

{
    "age": 21,
    "rol": "admin"
}

#### breed create
POST http://localhost:3000/api/v1/breeds
Content-Type: application/json

{
    "name": "callejero"
}

#### breed get
GET http://localhost:3000/api/v1/breeds

### login user

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "  ",
    "password": "  "
}

### register user

POST https://crud-postgres-render.onrender.com/api/v1/auth/register
Content-Type: application/json

{
    "username": "user1",
    "email": "example1@gmail.com",
    "password": "admin123"
}
### login user
POST https://crud-postgres-render.onrender.com/api/v1/auth/login
Content-Type: application/json

{
    "email": "example1@gmail.com",
    "password": "admin123"
}
### profile user
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzIzNzY5ODkyLCJleHAiOjE3MjM4NTYyOTJ9.F2L49vt_3-ld4Kl1KBJDopbNnQk5GE_UEoX9ykWv8qg

GET https://crud-postgres-render.onrender.com/api/v1/auth/profile
Authorization: Bearer {{authToken}}