### get cats
GET http://localhost:3000/api/v1/cats

### create cats
POST http://localhost:3000/api/v1/cats
Content-Type: application/json

{
    "name": "garfield",
    "age": 7,
    "breed": "persian"
}

### get cats by id
GET http://localhost:3000/api/v1/cats/75c50826-6953-49d2-a72c-3111ff8b5aac

### delete cats
DELETE http://localhost:3000/api/v1/cats/75c50826-6953-49d2-a72c-3111ff8b5aac

### create cats
PATCH http://localhost:3000/api/v1/cats/bf37cb27-0a59-443e-961e-29555c00ad90
Content-Type: application/json

{
    "age": 21,
    "rol": "admin"
}

#### breed create
POST http://localhost:3000/api/v1/breeds
Content-Type: application/json

{
    "name": "afgano"
}

#### breed get
GET http://localhost:3000/api/v1/breeds

